#ifndef __MOTO_MEM_RESERVE_H
#define __MOTO_MEM_RESERVE_H

#define RAMOOPS_CONSOLE_SIZE    0x80000    /* 512 KiB */
#define RAMOOPS_PMSG_SIZE       0x80000    /* 512 KiB */
#define RAMOOPS_RECORD_SIZE     0x300000   /* 3 MiB */
#define RAMOOPS_SIZE            (RAMOOPS_CONSOLE_SIZE + RAMOOPS_PMSG_SIZE + RAMOOPS_RECORD_SIZE)  // 5 MiB
#define RAMOOPS_BASE_ADDR       0x8a300000 // New base address

#define WDOG_CPUCTX_SIZE_PERCPU 0x5c00     /* sizeof(struct msm_wdog_cpuctx) */
#define WDOG_CPUCTX_SIZE_8CPUS  (WDOG_CPUCTX_SIZE_PERCPU * 8)
#define WDOG_CPUCTX_SIZE_4CPUS  (WDOG_CPUCTX_SIZE_PERCPU * 4)

#define WDOG_CPUCTX_END_ADDR    RAMOOPS_BASE_ADDR

#define WDOG_CPUCTX_SIZE        WDOG_CPUCTX_SIZE_8CPUS
#define WDOG_CPUCTX_BASE        (WDOG_CPUCTX_END_ADDR - WDOG_CPUCTX_SIZE_8CPUS)

#define TZLOG_BCK_SIZE          0x30000
#define TZLOG_BCK_BASE          (WDOG_CPUCTX_BASE - TZLOG_BCK_SIZE)

#define MMI_ANNOTATE_SIZE       0x800
#define MMI_ANNOTATE_BASE       (TZLOG_BCK_BASE - MMI_ANNOTATE_SIZE)

#endif /* __MOTO_MEM_RESERVE_H */